#!/bin/bash

set -ex

for component in ovn openvswitch; do
  for dir in log run etc; do
    mkdir -p $SNAP_COMMON/$dir/$component
  done
done

mkdir -p $SNAP_COMMON/run/dpdk

# P4 OVS
mkdir -p /etc/stratum
touch /etc/stratum/pipeline_cfg.pb.txt
mkdir -p /usr/share/target_sys
cp $SNAP/share/target_sys/zlog-cfg /usr/share/target_sys
